import React from 'react'
import { PrivateLayout } from '../../layout'

const StatisticsPage = () => {
    return (
        <PrivateLayout
        title="Shoppingify | Statistics"
        description="Statistics page"
    >
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et porro quidem assumenda enim magni deleniti sed eos id animi eius accusantium optio culpa, totam excepturi ab, praesentium ut molestiae. Qui.
        Aspernatur sint nostrum est amet provident ratione nesciunt id reprehenderit, soluta facere voluptas aperiam ut consequuntur possimus perspiciatis totam vel labore nam itaque recusandae dignissimos voluptates aut illum! Assumenda, in.
        Reprehenderit natus modi iste sapiente. Debitis veritatis veniam soluta tempora repudiandae ipsa voluptatem fugit libero quam fuga quas in consequatur doloremque amet explicabo id vitae quaerat porro, necessitatibus perferendis sint?
        Neque molestias modi repellendus. Reprehenderit asperiores incidunt nesciunt! Dolorum ea nemo eos dolores culpa. Sed, sunt eos facere nostrum asperiores pariatur minima molestias quidem atque aperiam neque sint perferendis in.
        Facere quam qui excepturi iusto, tenetur quibusdam perferendis ullam aspernatur hic, doloremque pariatur dolorum explicabo delectus autem est possimus aliquid consectetur! Doloribus molestias delectus deleniti? Repellat laboriosam excepturi amet quibusdam!
        Labore iure quas odio rerum provident sequi itaque tempore temporibus eveniet distinctio, velit sit fuga laudantium nemo voluptates officiis iste? Incidunt consectetur ipsam velit sunt, expedita iure dolorem recusandae mollitia.
        Nam beatae ratione iusto totam enim debitis alias, deleniti sed eum natus ullam sequi ex animi ut reprehenderit, harum maiores suscipit cum. Maxime quibusdam, et aut minima nemo voluptatem eius!
        Sint architecto dicta autem earum et quam tempore, expedita corporis. Tenetur, aut! Expedita quisquam iusto voluptate molestias tempore inventore sed hic ipsa iure odit, fugiat nihil vitae obcaecati sint asperiores!
        Et minima itaque provident illum laudantium. Recusandae eveniet atque impedit mollitia nulla harum voluptas temporibus nesciunt maiores numquam quidem error accusamus, commodi animi minus obcaecati adipisci blanditiis cumque illo? Tempore!
        Possimus nisi odio ut earum ipsa esse distinctio iure reiciendis nihil, maiores commodi! Quo consequuntur nemo provident! Officia quas natus consectetur, delectus atque maiores provident, suscipit obcaecati placeat distinctio est?
        At, deleniti officiis soluta iusto, magni repellendus vel officia veritatis rem dolore eos ea nisi tempore maxime! Architecto cupiditate voluptatem, tempore cumque velit rerum quaerat soluta. Quasi illo unde qui.
        Excepturi temporibus vitae iste quam voluptate impedit iusto sed ducimus sit commodi et quia maiores, illum, tempora pariatur est nisi? Ipsam dolorum minus similique in aliquid. Nisi repellat reiciendis hic.
        Assumenda accusantium corrupti fugit numquam alias fuga enim. Accusantium quod aliquid deserunt facere excepturi recusandae obcaecati incidunt hic necessitatibus! Facilis aut beatae corrupti deleniti doloremque quaerat? Temporibus at a reiciendis!
        Provident ad iste modi natus in, laudantium ullam nostrum dicta earum blanditiis ipsa ratione beatae ipsam omnis, dolorem ut mollitia veritatis reiciendis ex. Reprehenderit obcaecati odit dolore enim, provident quibusdam.
        Ipsam provident voluptates blanditiis omnis aspernatur laboriosam maxime fugiat. Accusantium quam omnis cumque totam dolorum iste corporis sint laboriosam cum impedit, consequuntur ullam recusandae, aliquid eius labore. Aliquid, error eveniet!
        Veritatis praesentium totam accusantium ad nostrum corrupti sint, amet voluptate, non beatae et ratione? Dicta, perspiciatis aperiam. Neque explicabo officia officiis placeat saepe maxime. Eos consectetur odit suscipit rerum cum!
        Repudiandae accusamus molestias architecto fuga fugiat totam labore dolores doloribus mollitia molestiae ipsam optio quae quibusdam natus veniam saepe rem neque incidunt fugit, asperiores dolor. Animi neque exercitationem minus odit?
        Mollitia inventore soluta aliquam aperiam in consectetur, voluptates quis nobis sed illo earum possimus dolores modi! Hic et optio illum inventore iusto molestiae tempore. Natus numquam earum fugit facere nihil.
        Tenetur exercitationem ullam maxime laborum explicabo quod eius tempore. Quasi quaerat, voluptatibus illum ullam voluptatum non quibusdam beatae nesciunt necessitatibus, ab alias. Magnam explicabo, porro eum nulla iure magni quod.
        Quis unde quaerat corrupti ratione, nulla, beatae nemo necessitatibus non harum illum, amet quo expedita eos temporibus laboriosam maiores? Officia distinctio ut odit cumque cupiditate nesciunt, maiores quo nulla porro?
        Officiis, quis? Ipsa sit ut eius sequi est distinctio iusto nulla error vel praesentium earum labore commodi delectus minus omnis, assumenda animi iure neque quod nesciunt id, pariatur at asperiores.
        Pariatur corrupti libero perspiciatis harum vel, aspernatur eveniet saepe soluta sed nulla sequi exercitationem atque asperiores maxime suscipit fugit repellendus neque? Neque voluptas porro dolorum exercitationem error, aut odit in.
        Accusantium nesciunt, provident quia maxime eum repellendus voluptates laboriosam aliquam accusamus tenetur sint hic dolores a itaque vero id temporibus debitis impedit illo consequuntur saepe earum esse ipsa quibusdam! Dicta.
        Cumque eius optio iure impedit accusantium numquam, at ab, nisi natus praesentium amet delectus. Unde error assumenda ipsum consequuntur tempora, aliquid molestiae consectetur eos reiciendis. Quae dolor commodi blanditiis dolores!
        Sed nostrum totam alias aut provident aperiam. Natus consequatur minima libero voluptatum asperiores nobis molestiae ad obcaecati possimus, dolores rerum, repellendus iste ea veniam ducimus corporis illum quia necessitatibus enim.
        Molestias, facilis. Maiores hic quisquam delectus odio eum esse ab, ullam in magnam tempore ex a qui asperiores voluptatum veniam eligendi voluptatibus quas earum facilis. Doloremque dolore consequuntur quia beatae?
        Quas excepturi eaque at commodi eligendi voluptates sint repudiandae deleniti illo. Voluptates reiciendis praesentium deleniti saepe accusantium temporibus ratione ea eveniet laudantium, quam cupiditate exercitationem quae minus? Illum, omnis quasi?
        Omnis fugiat suscipit adipisci! Incidunt, esse quas. Doloremque qui adipisci, similique maxime excepturi ipsum nulla quaerat, nostrum, rerum odit sunt nihil nemo delectus voluptate doloribus rem ipsa ut optio ratione?
        Harum, illo iure officia facere quibusdam eveniet fugit iusto corrupti! Maxime accusantium quibusdam voluptate consequuntur et. Dolore sapiente nulla hic? Assumenda distinctio accusamus inventore esse molestiae dolore maxime. A, facere!
        Repudiandae laborum minima quibusdam ullam cum quisquam at porro maxime atque nam blanditiis beatae unde rem quis incidunt tempore, ducimus aliquid fugiat rerum magnam molestias asperiores. Nemo dolorum vero voluptas!
        Quo asperiores optio inventore ad sunt, adipisci, fugit in voluptates repudiandae voluptatum consectetur corrupti deserunt expedita ipsa? Asperiores, illum deserunt necessitatibus eligendi veritatis ullam officiis voluptatibus rerum blanditiis perferendis quas.
        Quidem explicabo labore nesciunt autem ad voluptatum rem eius nulla ipsa eveniet quas voluptas, expedita facilis culpa totam velit neque voluptatibus! Consequatur, aut. Nisi aperiam debitis laborum ad. Optio, est.
        Numquam dolore possimus dolorem veniam aperiam placeat sequi, atque laudantium, nesciunt tempora dolores suscipit est aut expedita, velit eligendi vero. Eum vero consequatur officia nobis dolore ad recusandae minima dolor?
        Eaque labore animi sunt impedit modi numquam hic at adipisci accusamus voluptate harum assumenda rerum, aut laborum voluptatum amet illo officia laboriosam exercitationem, aliquam consectetur. Quisquam quaerat sit dolorum molestiae?
        Nihil, saepe quasi nam delectus sint tenetur, molestias aliquam consectetur quas, minima aspernatur autem animi assumenda eos recusandae sit error reprehenderit omnis corrupti. Qui ab illum, eos repellat nihil porro.
        Sed quaerat similique itaque quisquam vel molestias, consectetur deleniti blanditiis pariatur amet dicta tenetur sapiente vitae. Culpa fuga quasi, optio nisi assumenda cumque reiciendis tempora aliquam nesciunt, quos accusamus libero.
        Eaque iste in assumenda vitae vel voluptate, at nostrum a voluptates minus impedit illo recusandae odit distinctio dignissimos, ea placeat, odio incidunt unde. Nobis nulla obcaecati sapiente, architecto culpa distinctio?
        Vel expedita quod nam recusandae officiis dolores dignissimos provident distinctio! Voluptatum accusamus quos sint aperiam iste enim ipsum nisi, eveniet minima! Nobis, illum porro! Iste ratione exercitationem laudantium nulla molestias.
        Corporis, necessitatibus sequi in aperiam aliquid maxime mollitia quo a. Inventore enim nihil ex ea cupiditate quis quo veritatis quaerat ad? Laudantium sapiente magni quisquam possimus voluptatibus totam soluta neque.
        Repellendus animi, velit autem possimus odio, numquam, libero suscipit eaque vitae illum accusantium in aliquam ad culpa rerum tempore iusto dolor ex. Assumenda, fuga provident aperiam quasi praesentium nobis illum!
        Ipsum expedita magni totam repudiandae recusandae consequuntur quaerat libero! Quam laudantium perspiciatis nemo aperiam, alias expedita, eaque fugit veniam enim odit debitis autem quasi rerum nulla accusamus modi voluptatem facilis!
        Amet, in ipsum eaque sapiente natus ratione, voluptas a nostrum assumenda porro repellat illum vitae expedita eius accusantium saepe neque laudantium fugiat. Pariatur adipisci et accusantium fuga ducimus nulla modi.
        Fugiat repudiandae maiores quod amet aperiam a libero corporis provident perspiciatis nihil tempore voluptas recusandae qui voluptates ad molestiae, aut, atque at officiis omnis iusto eius accusantium commodi saepe. Officia.
        Quisquam eum tenetur accusamus asperiores numquam quas itaque. Iure reiciendis voluptates laborum ex ipsum fugiat voluptatibus, quaerat consequuntur facere eius iusto doloribus eaque velit eligendi nesciunt saepe. Veniam, velit voluptate.
        Dicta, consequatur repellendus! Quis quod aperiam hic voluptas obcaecati fuga ipsam neque voluptatum, dolorem laborum delectus odit? Eum illum vel corporis nihil facere consectetur, ratione dolore molestiae, iure adipisci provident?
        Neque sed exercitationem quod blanditiis, praesentium, aut quidem reprehenderit illum aspernatur quia eaque animi corrupti repudiandae beatae repellendus vitae, et odio consequatur sit dignissimos ut nam nemo voluptas asperiores? Similique.
        Delectus laboriosam a aliquid itaque, asperiores ullam totam aspernatur incidunt deserunt soluta officia minus eligendi et odio molestias culpa, optio, ab tempore assumenda dicta corporis? Inventore iste magni officiis vitae.
        Eaque modi labore exercitationem officiis tempore ad obcaecati et a, quibusdam aut repudiandae voluptatem, temporibus, sed enim. Maxime ipsa officiis excepturi tenetur. Praesentium modi, dolorem maiores quod distinctio voluptates repellendus?
        Corrupti dolorem aperiam itaque ad a recusandae cum nulla odio? Officiis libero autem deleniti, ratione sequi nesciunt! Ab ducimus amet ullam iste, repudiandae autem excepturi impedit, quisquam ex accusantium quo?
        Animi eos nam sit magnam perferendis? Cupiditate maiores soluta magnam non nemo. Hic rerum cum, consectetur deleniti distinctio sit necessitatibus voluptatem, adipisci placeat expedita quisquam doloremque odit eius eos corporis!
        Sequi quas error quaerat alias nisi aperiam maxime quos, aliquid voluptates optio itaque neque tempore? Ut maiores consequatur eligendi officia dolor dolorum inventore voluptate? Illo nobis nam laudantium magni officiis!
        Tempore labore tempora et sapiente eum atque, ratione at rerum debitis? Perferendis ullam beatae quasi laboriosam quas quo rerum unde saepe, nam nemo accusantium alias iusto ad! Iure, incidunt earum?
        Dicta rerum facere praesentium dolor iure blanditiis et cum nesciunt incidunt. Quisquam, facilis illum blanditiis vel, quidem placeat, porro qui ducimus perferendis exercitationem dicta odio repellendus assumenda dolorem provident laborum.
        Aliquam, velit maiores numquam, obcaecati nam possimus quis deleniti earum, distinctio cum mollitia quasi itaque tenetur ex totam molestiae! Dolores est ut nulla, facere expedita cumque laboriosam nihil. Temporibus, nobis.
        Labore cumque perspiciatis sint facere in fugiat. Ipsa, maiores. Aliquid omnis cumque ullam! Quaerat aperiam maiores dolorum voluptatum dolores ducimus quibusdam tempora. Delectus necessitatibus id nemo culpa nostrum, animi voluptates?
        Earum est sapiente autem velit amet, alias quaerat architecto facere ducimus nobis voluptatum nulla? Sed atque, labore consectetur doloremque magni reiciendis, velit neque soluta ex ab omnis ratione libero voluptatem.
        Necessitatibus iusto veniam tenetur sequi, corporis eum quas iste, et hic saepe id similique. Molestias quam, nisi, mollitia, ex recusandae enim consequuntur nesciunt exercitationem facere aperiam blanditiis ducimus dolor impedit.
        Iusto, fuga sequi eveniet dignissimos similique dolor magni culpa natus earum nisi officiis minus doloribus autem nostrum quia inventore maxime esse beatae nemo. Maiores, minus eum. Voluptas sit non iusto.
        Quasi reprehenderit dolor praesentium laboriosam tempore sed, corporis voluptas fugit quod in! Ullam, delectus, atque eveniet nemo consequuntur voluptatibus aperiam consectetur esse inventore animi placeat incidunt, quo similique. Eligendi, dolore!
        Esse nulla, eos quia quasi deserunt aliquam optio quod voluptatibus numquam consequuntur ipsa magnam nihil modi accusamus temporibus. Nisi eius excepturi rerum officia ipsa porro itaque commodi nostrum sed voluptate.
        Voluptatem perferendis incidunt veniam id. Placeat nemo, cupiditate error, facilis ut aut consectetur ullam sunt porro sit laboriosam iusto possimus sed repudiandae iure itaque aspernatur eveniet assumenda excepturi maxime sint.
        Nemo commodi sed eveniet voluptates! Perferendis beatae ad velit aut iure ipsum, magni aperiam porro veritatis dicta earum iste facere a saepe cum, voluptatibus excepturi quod alias voluptates laudantium quo.
        Veritatis, illum, pariatur quasi soluta adipisci nesciunt deserunt, nemo repellendus ducimus ratione quo ab nobis voluptas ipsam! Neque aliquid recusandae quis adipisci eius minima atque, distinctio voluptatem eos. Repellat, incidunt.
        Ratione corrupti odio natus voluptate dicta possimus velit excepturi delectus quibusdam officia. Recusandae beatae atque, qui nemo, ex neque minus veritatis corrupti impedit, iure ipsa esse. Recusandae quisquam laborum nihil!
        Mollitia, molestias id? Delectus nisi libero possimus earum quo deleniti eos distinctio consectetur pariatur, iste est deserunt, voluptas dolorum? Accusantium commodi cumque delectus iste quisquam maiores sit, porro autem assumenda.
        Pariatur et architecto amet dolorum veritatis, repellat illum debitis facilis enim totam animi aliquid, consequuntur, incidunt harum maiores at quo qui? Voluptatem facilis impedit eligendi enim! Fuga possimus vel delectus.
        Excepturi eaque, officia accusamus omnis placeat delectus alias natus optio, fuga, animi distinctio pariatur quae! Iusto ea sit omnis! Nam, quidem? Voluptatum laboriosam temporibus sint porro aliquam ratione quis dignissimos?
        Earum, assumenda iusto. Porro doloremque eius magnam explicabo quas, exercitationem nesciunt. Voluptas ipsum molestiae veritatis. Quas voluptatem obcaecati, libero ad corporis aspernatur totam, culpa repudiandae magni incidunt distinctio minus corrupti?
        Vel doloribus esse adipisci cumque eaque ipsa voluptate deserunt modi accusamus sed suscipit enim optio temporibus corporis ex laboriosam, perferendis quo. Enim magnam neque repudiandae ipsa ipsum reprehenderit, accusamus qui.
        Corporis voluptatum rem sint suscipit incidunt mollitia minus maiores inventore aperiam. Nobis nam ullam quaerat deleniti dolore quam perferendis commodi repudiandae voluptatibus culpa ab ipsam, vel molestiae tenetur aliquam rem.
        Necessitatibus nisi voluptate deserunt sequi itaque cumque neque accusamus in, culpa odit possimus dolor saepe, omnis soluta unde tempora animi. Voluptate dolorum, cupiditate est architecto provident velit odio error nam.
        Perspiciatis quam accusamus quis velit facilis adipisci ipsum eaque similique, cumque quod, neque voluptatibus incidunt sed placeat tempore modi quisquam maxime repellat. Minus sequi eum dolore consequuntur obcaecati vitae? Minima.
        Qui ea beatae, possimus eius quasi perferendis iste fugit vel et, eaque veritatis, architecto odit cupiditate aliquid totam nobis nulla. Doloribus aliquam dolorem commodi iure in. Cum ipsam cumque sunt.
        Officiis placeat ad quaerat voluptatum iure voluptas. Necessitatibus, facilis placeat eveniet beatae, facere mollitia sunt id animi enim eius nam odio delectus corrupti nostrum tempore recusandae quas quia deserunt voluptate.
        Architecto odit numquam eaque possimus nobis recusandae, dolores hic. Inventore, incidunt repellendus tempore, provident at in esse sequi dolorum cupiditate ipsam suscipit ipsum fugiat, tenetur eligendi architecto fuga est non.
        Eius, animi. Doloremque, laboriosam repellendus culpa aliquam nobis aspernatur eligendi, magni incidunt velit rem quia pariatur necessitatibus architecto commodi, voluptate totam a sint asperiores! Nisi architecto ut beatae commodi maxime?
        Voluptas ut iure error asperiores, obcaecati distinctio, sint non quasi esse accusamus, similique doloribus odio blanditiis recusandae! Enim explicabo officia neque accusantium! Necessitatibus facilis aut modi ut cumque ipsa commodi.
        Repudiandae quasi modi maiores? Animi deleniti numquam sed nobis ad quam est debitis iusto sit qui quos eum ab modi omnis minima quisquam suscipit ratione, perferendis perspiciatis veritatis? Esse, assumenda.
        Laudantium ipsam reprehenderit provident assumenda ea eos quidem exercitationem sunt eligendi nostrum sed ab, commodi, libero nobis qui molestiae, accusantium nesciunt ipsum? Molestiae placeat nihil neque distinctio fugit ad quia.
        Odit enim laudantium velit numquam doloremque neque aspernatur ea assumenda ab blanditiis dicta incidunt, fugiat excepturi iusto minus ratione facere id commodi aliquam. Accusantium commodi illo tempore fugit? Quae, aperiam.
        Harum vel quasi tempora asperiores nesciunt non inventore eos alias laboriosam vero a enim, ea ullam sapiente iste velit nisi magnam! Vero eum veritatis autem pariatur, doloremque deserunt doloribus praesentium?
        Maxime non cum, sapiente in placeat at repudiandae cupiditate iste cumque corrupti animi soluta corporis maiores vitae aut tenetur! At laudantium soluta eum inventore. Magnam dolores labore beatae alias ratione.
        Illum laudantium temporibus, consectetur numquam dolore ducimus impedit eum optio? Aut optio, ab vero harum sit molestiae quod velit soluta amet, suscipit officiis id! Optio numquam voluptate tenetur culpa accusantium.
        Quidem distinctio fuga doloribus, magni ea voluptatibus consectetur a itaque magnam enim harum eos debitis commodi vel maiores, nisi explicabo exercitationem, quae tempora aliquid reprehenderit minima nulla. Quia, in laborum?
        Reiciendis expedita similique tenetur illum provident eaque dolore at. Aliquid voluptatum repellat accusamus tempore asperiores repellendus porro? Maiores ipsam unde ad ducimus possimus, magni reprehenderit, odio, officiis obcaecati eligendi assumenda!
        Nobis, ea et. Esse nostrum cum nobis asperiores corrupti facere magni consequatur officia quis alias provident perferendis at dolorem vitae adipisci, modi ratione delectus repudiandae nulla autem nemo a? Cum!
        Ipsam, eaque ad distinctio tempore architecto quasi iste recusandae eos atque, incidunt tempora adipisci vero, consequatur inventore. Culpa doloribus tempore illum, voluptate quos nulla eligendi quisquam quam, facere sequi tenetur!
        Obcaecati assumenda expedita velit ipsum ad tenetur repudiandae, eligendi odio similique, et necessitatibus eos itaque inventore recusandae magnam exercitationem quia hic animi, beatae tempora fuga voluptatem. Possimus tempora quos vitae?
        Ea aliquid magnam fugit optio sint perferendis omnis voluptatibus totam. Quia obcaecati laudantium reiciendis distinctio atque voluptatem sint sunt vel minus nam maiores quidem, ducimus, incidunt vero culpa ea consequuntur.
        Consequuntur earum ullam quam consequatur? Perspiciatis voluptas aut consequatur vel alias veniam adipisci nam, iste ipsa expedita, laudantium, iusto eos odio. Non autem repellat reprehenderit libero, quas maiores dignissimos nostrum.
        Ipsa quibusdam voluptate molestiae iste! Ab et consectetur iusto vero voluptatum in iure, ex culpa dolorem commodi incidunt, impedit ut quas similique assumenda mollitia quaerat fugit reprehenderit. Rerum, vitae praesentium?
        Ab repellat ea voluptas sit, ratione sequi neque harum quaerat quos deserunt eius praesentium debitis consectetur velit omnis eaque doloribus, enim a, incidunt quasi molestias tempore impedit ipsum. Doloribus, voluptatem.
        Modi ea magnam corrupti soluta, sit praesentium perspiciatis! Ea rerum nulla veritatis exercitationem perferendis at possimus, repellendus ex neque aspernatur! Itaque dolor adipisci suscipit corporis cum et repudiandae enim ipsam?
        Alias fugit labore repudiandae molestias repellendus, maxime suscipit excepturi id, maiores saepe mollitia doloremque quas possimus. Ex, quisquam laborum! Ducimus voluptatibus voluptatum totam illo non. Quo perferendis temporibus hic corrupti.
        Hic cupiditate ad natus autem minima animi incidunt rem atque amet. Magni dolores veniam eius provident fugiat. Quibusdam, maxime quis! Exercitationem officia cupiditate eum rem dolorum, cum nisi quibusdam quam?
        Expedita sapiente repellat consequatur ducimus aliquid facere enim autem, sit tenetur quis temporibus eligendi dolor excepturi voluptate sed numquam exercitationem fuga molestiae labore harum ipsam necessitatibus accusantium. Eos, itaque recusandae?
        Porro fuga amet laudantium fugiat cumque. Accusamus laborum harum labore repellat reiciendis consectetur, dignissimos esse, ab id odio voluptate sapiente rem magni! Quam, repellendus enim commodi exercitationem soluta perspiciatis incidunt.
        Vitae soluta cupiditate rem dolore sequi voluptates, quod temporibus dolores eligendi, reiciendis deleniti consequuntur minima veritatis molestias. Exercitationem, explicabo. Soluta doloribus delectus officia ducimus ea labore, atque ex! Voluptatem, praesentium.
        Voluptas similique fugiat, ipsam unde libero nulla adipisci perferendis hic. Quos nobis a, velit blanditiis laborum repellendus alias non, veritatis, libero cumque rerum labore dignissimos dolor eius fugiat incidunt magni.
        Unde autem illo magnam repellendus dolorem quibusdam, laudantium natus libero praesentium reprehenderit amet aspernatur eaque maxime ducimus exercitationem qui doloremque odio iusto assumenda perspiciatis ad dolor? Mollitia aliquid harum placeat?</div>
    </PrivateLayout>
    )
}

StatisticsPage.auth = true;

export default StatisticsPage