export * from './category.interface'
export * from './user.interface'
export * from './product.interface'
export * from './activePurchase.interface'
export * from './pruchase.interface'
export * from './animations.interface'